"""empty message

Revision ID: 19618f3a4672
Revises: cdd79c0c05f6
Create Date: 2017-09-07 13:24:01.232836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19618f3a4672'
down_revision = 'cdd79c0c05f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results', sa.Column('pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_results', 'pic')
    # ### end Alembic commands ###
