"""empty message

Revision ID: 541b8b03717f
Revises: e22ba0b4a692
Create Date: 2017-08-09 14:02:59.346026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541b8b03717f'
down_revision = 'e22ba0b4a692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invalid')
    # ### end Alembic commands ###
