"""empty message

Revision ID: ac55f42f620f
Revises: 
Create Date: 2017-08-09 01:57:13.580251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac55f42f620f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('r_model', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('stripe', sa.String(), nullable=True),
    sa.Column('electronics', sa.Boolean(), nullable=True),
    sa.Column('convenience', sa.Boolean(), nullable=True),
    sa.Column('painted_roof', sa.Boolean(), nullable=True),
    sa.Column('build_date', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('dealer', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
