"""empty message

Revision ID: cdd79c0c05f6
Revises: 541b8b03717f
Create Date: 2017-09-07 12:38:15.541554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd79c0c05f6'
down_revision = '541b8b03717f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('dealer', sa.String(), nullable=True),
    sa.Column('distance', sa.String(), nullable=True),
    sa.Column('listing', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('cars', 'painted_roof')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('painted_roof', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('search_results')
    # ### end Alembic commands ###
