"""empty message

Revision ID: e22ba0b4a692
Revises: ac55f42f620f
Create Date: 2017-08-09 05:23:47.172512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22ba0b4a692'
down_revision = 'ac55f42f620f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'price')
    op.drop_column('cars', 'url')
    op.drop_column('cars', 'dealer')
    op.drop_column('cars', 'address')
    op.drop_column('cars', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars', sa.Column('dealer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
